- lib/commands/asm/vm/vmclient.js
Added check for OpenSSL in "create docker vm" command
> Added check for OpenSSL in "create docker vm" command

- lib/commands/asm/network/vnetUtil.js
- lib/commands/asm/vm._js
- lib/commands/asm/vm/vmclient.js
Fixing following issues:
https://github.com/Azure/azure-xplat-cli/issues/1566
https://github.com/Azure/azure-xplat-cli/issues/1583
https://github.com/Azure/azure-xplat-cli/issues/1554
https://github.com/Azure/azure-xplat-cli/issues/1500
https://github.com/Azure/azure-xplat-cli/issues/1516
https://github.com/Azure/azure-xplat-cli/issues/1594
https://github.com/Azure/azure-xplat-cli/issues/1416
https://github.com/Azure/azure-xplat-cli/issues/1589
https://github.com/Azure/azure-xplat-cli/issues/1569
> Multiple bug fixes

- lib/commands/asm/vm/vmclient.js
Changed default Docker extension version to "0.6" in "vm docker create" command.
> Changed default Docker extension version to "0.6" in "vm docker create" 

- lib/commands/arm/vm/vm._js
- lib/commands/arm/vm/vmClient._js
Added --quiet param to vm extension uninstall command
> Added --quiet param to vm extension uninstall command

- lib/commands/arm/network/network._js
- lib/commands/arm/vm/vm._js
Addressing https://github.com/MSOpenTech/azure-xplat-cli-pr/issues/376
> Addressing text review comments

- lib/commands/arm/vm/vm._js
- lib/commands/arm/vm/vmClient._js
Implemented 'vm disk list' command
> Implemented 'vm disk list' command

- lib/commands/arm/network/dnsRecordSet._js
- lib/commands/arm/network/lbShowUtil._js
- lib/commands/arm/network/nic._js
- lib/commands/arm/network/vnetShowUtil._js
- lib/commands/arm/network/vpnGateway._js
- lib/util/logging.js
refacrtored show commands utils.
reworked usages
> dev-network-show-fixes -> dev

- lib/commands/asm/network._js
- lib/commands/asm/network/networkClient._js
- lib/commands/asm/network/subnet._js
asm nsg subnet add implemented
> asm vnet subnet create/list/show/delete implemented

- lib/commands/asm/network._js
- lib/commands/asm/network/networkClient._js
- lib/commands/asm/network/vpnGateway._js
* VPN gateways: show, delete implemented
* ASM: 'network vent list' output fixed
> VPN gateways: show, delete implemented

- lib/commands/asm/network._js
replaced  according to documentation in network._js file
> moved asm vnet subnet commands block

- lib/commands/arm/network/networkClient._js
* moved SOA parameters prompt to proper function.
> Fixed Azure bug 1764.

- lib/commands/arm/network/network._js
Changed 'dns-zone record-set' to 'dns-record-set'.
> Fixed Azure bug 1776.

- lib/commands/arm/network/dnsRecordSet._js
* removed look up before list
* removed location column
* type column is truncated to show only the DNS type
* added nextLink
> Fixed Azure bug 1779.

- lib/commands/asm/vm._js
- lib/commands/asm/vm/vmclient.js
1. Added support for multiple NICs
2. Some code re-factoring to avoid code duplication
> Adding support for virtual machine NICs. Addressing issue https://github.com/Azure/azure-xplat-cli/issues/1785

- lib/commands/arm/network/network._js
https://github.com/Azure/azure-xplat-cli/issues/1767 issue fixed
> Fixed Azure issue 1767

- lib/commands/arm/network/network._js
https://github.com/Azure/azure-xplat-cli/issues/1768 issue fixed
> Fixed Azure issue 1768

- lib/commands/arm/network/dnsZone._js
https://github.com/Azure/azure-xplat-cli/issues/1770 issue fixed
> Fixed Azure issue 1770

- lib/commands/arm/network/dnsZone._js
https://github.com/Azure/azure-xplat-cli/issues/1771 issue fixed
> Fixed Azure issue 1771

- lib/commands/arm/network/network._js
https://github.com/Azure/azure-xplat-cli/issues/1773 issue fixed
> Fixed Azure issue 1773

- lib/commands/arm/network/dnsZone._js
https://github.com/Azure/azure-xplat-cli/issues/1775 issue fixed
> Fixed Azure issue 1775

- lib/commands/arm/network/dnsRecordSet._js
- lib/commands/arm/network/networkClient._js
* removed look up after update.
* added prompt before deleting.
> Fixed Azure bug 1783.

- lib/commands/arm/network/dnsRecordSet._js
- lib/commands/arm/network/network._js
- lib/commands/arm/network/networkClient._js
* removed look ups before create
* changed TTL validation logic
* added type parameter as mandatory
> Fixed Azure bug 1777.

- lib/commands/arm/network/dnsRecordSet._js
* Removed 'Record1, Record2, etc..' on each line of actual record data.
* Changed labels to exact same terminology as in CloudDNS.
> Fixed Azure bug 1781.

- lib/commands/arm/network/network._js
Referenced issue https://github.com/Azure/azure-xplat-cli/issues/1780.
> Network ARM: Updated help description for 'dns-record-set show' command

- lib/commands/arm/network/dnsRecordSet._js
* removed look ups before delete.
> Fixed Azure bug 1782.

- lib/commands/arm/network/dnsZone._js
https://github.com/Azure/azure-xplat-cli/issues/1769 issue fixed
> Fixed Azure issue 1769

- lib/commands/asm/network/nsg._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/189 issue fixed
> ASM: Avoiding lookup for NSG create, delete

- lib/commands/asm/network._js
- lib/commands/asm/network/networkClient._js
- lib/commands/asm/network/routeTable._js
- lib/commands/asm/network/vpnGateway._js
refactored 'subnet route-table' add/delete/show commands
> moved existing 'subnet route-table' functionality to separate file.

- lib/commands/asm/network/constants._js
added constants._js file to separate valid values
> Dev asm network description refactoring

- lib/commands/asm/network._js
- lib/commands/asm/network/constants._js
- lib/commands/asm/network/localNetwork._js
- lib/commands/asm/network/networkClient._js
- lib/commands/asm/network/vpnGateway._js
ASM VPN Gateways:
*  create,
*  resize,
*  reset, 
* set local site, 
* delete local site 
implemented
> ASM VPN Gateways: create, resize, reset, set local site, delete local site

- lib/commands/asm/network._js
> Network ASM: resolved issue #191

- lib/commands/asm/network._js
- lib/commands/asm/network/networkClient._js
- lib/commands/asm/network/routeTable._js
This PR contains following: 
* route-table create
* route-table show 
* route-table list
* route-table delete
> Network ASM: route-table commands implemented.

- lib/commands/asm/network/localNetwork._js
resolved issues after code review
> asm 'local-network create/set commands'

- lib/commands/arm/vm/networkNic._js
- lib/commands/arm/vm/networkPublicIP._js
- lib/commands/arm/vm/networkVNet._js
- lib/commands/arm/vm/networkVNetSubnet._js
- lib/commands/arm/vm/vmImage._js
- lib/commands/arm/vm/vmOsProfile._js
- lib/commands/arm/vm/vmProfile._js
- lib/commands/arm/vm/vmStorageProfile._js
If there is a choice between multiple options command will throw an
exception.
If there is only one missing option command will prompt for it.
> Changed VM create command to prompt missing options

- lib/commands/asm/network._js
- lib/commands/asm/network/constants._js
- lib/commands/asm/network/networkClient._js
- lib/commands/asm/network/routeTable._js
ASM Routes: 
* add route, 
* remove route implemented
> ASM Routes: add route, delete route

- lib/commands/asm/network._js
- lib/commands/asm/network/networkClient._js
- lib/commands/asm/network/vpnGateway._js
This PR contains:
* shared-key commands: set, reset
* vpn-devices commands: list, get-script
* diagnostics commands: start, stop, get
* resolved minor 'nsg rule' issues 
**Please note, the following commands is not finished yet:**
* vpn-devices get-script
* diagnostics stop
> Network ASM: shared-key, vpn-devices, diagnositcs commands implemented.

- lib/commands/asm/network._js
- lib/commands/asm/network/subnet._js
removed extra-method to get vnet by name - use utils instead
resolved issues with warnings/errors
> reworked asm vnet subnet

- lib/commands/asm/network/localNetwork._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/230 issue updated
> ASM Local Network add: 'warn' issue fixed

- lib/commands/asm/network/appGateway._js
Added proper --json parameter handling.
> Network ASM: Fixed 'application-gateway show' command.

- lib/commands/asm/network/appGateway._js
> Network ASM: added 'description' parameter for 'application-gateway show' command

- lib/commands/asm/network/vpnGateway._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/245 issue fixed
> ASM vpn gateway list fixed

- lib/commands/asm/network._js
- lib/commands/asm/network/appGateway._js
- lib/commands/asm/network/constants._js
- lib/commands/asm/network/networkClient._js
- lib/util/utils.js
* import config, export config
* address-pool: add, remove 
* http-settings: add, remove 
* frontend-ip: add
implemented
> ASM App Gateway:  configuration elements implemented

- lib/commands/asm/network._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/273 issue fixed
> local-network commands fixed

- lib/commands/asm/network._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/271 issue fixed
> ASM TM: enable, disable commands description fixed

- lib/commands/asm/network._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/281 issue fixed
> azure network -h help fixed

- lib/commands/asm/network/localNetwork._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/278 issue fixed
> ASM local-network: create, set. Add vpn-gateway-address validation

- lib/commands/asm/network/trafficManager._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/272 issue fixed
> ASM: TM enable, disable --json option handled

- lib/commands/asm/network/vpnGateway._js
> Network ASM: fixed 'gateway vnet diagnostics stop' command

- lib/commands/asm/network/localNetwork._js
> Fixing jshint issue in localNetwork._js

- lib/commands/arm/vm/vm._js
- lib/commands/arm/vm/vmClient._js
- lib/commands/arm/vm/vmExtensionProfile._js
- lib/commands/asm/vm._js
- lib/commands/asm/vm/vmclient.js
>  Changed 'vm docker create' command to use new Docker extension

- lib/commands/asm/network/localNetwork._js
> Network ASM: fixed 'local-network remove' command

- lib/commands/asm/network/localNetwork._js
> Network ASM: changed error message in 'local-network remove' command

- lib/commands/asm/network/appGateway._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/317 issue fixed
> ASM App Gateway: address pool ip validation added

- lib/commands/asm/network/appGateway._js
- lib/util/vnet.util._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/317 issue fixed
> ASM App Gateway: address-pool DNS validation added

- lib/commands/asm/network._js
- lib/commands/asm/network/appGateway._js
- lib/commands/asm/network/constants._js
- lib/commands/asm/network/networkClient._js
- lib/util/utils.js
ASM app gateways commands to manage frontend IPs, frontend ports, http listeners and load balancing rules are implemented
> asm app gateways commands implemented

- lib/commands/asm/network._js
> Fix ASM: 'network dnsserver list' command

- lib/commands/asm/network/appGateway._js
> ASM: 'app-gateway http-listener' commands. Improving validation, fixing wrong parameter

- lib/commands/asm/network._js
- lib/commands/asm/network/constants._js
- lib/commands/asm/network/networkClient._js
- lib/commands/asm/network/trafficManager._js
ASM: TM Endpoints commands: create, update, delete are implemented
> ASM: TM Endpoints commands: create, update, delete are implemented

- lib/commands/arm/network/vnetShowUtil._js
> Network ARM: fixed DNS servers label

- lib/commands/asm/network/subnet._js
https://github.com/MSOpenTech/azure-xplat-cli/issues/380
> ASM Subnet create fixed

- lib/commands/arm/network/dnsRecordSet._js
- lib/commands/arm/network/network._js
> Network ARM: moved promptRecordParameters function to dnsRecordSet._js

- lib/commands/asm/network/subnet._js
replaced subnet creation with association error
> resolved bug https://github.com/MSOpenTech/azure-xplat-cli/issues/380

- lib/commands/asm/network/trafficManager._js
> Resolved issue with property name

- lib/util/utils.js
- package.json
Reverts MSOpenTech/azure-xplat-cli#416
> Revert "Use azure-arm-network package instead of local files"

- lib/util/utils.js
- package.json
Reverts MSOpenTech/azure-xplat-cli#418
> Revert "Revert "Use azure-arm-network package instead of local files""

- lib/commands/arm/network/loadBalancer._js
This PR removes multi VIP check to allow more than one frontend IP.
Also it fixes indent check
> Removing Multi Vip Check to allow more than one frontend IP
